package movieproject;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import java.time.LocalDate;

/**
 *
 * @author awday
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    
    private String customerAddState = "";
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        querySelect = new javax.swing.JComboBox<>();
        executeQuery = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextPane();
        custFN = new javax.swing.JTextField();
        custLN = new javax.swing.JTextField();
        custE = new javax.swing.JTextField();
        custPN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        custM = new javax.swing.JTextField();
        custD = new javax.swing.JTextField();
        addCustomerButton = new javax.swing.JButton();
        custID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        deleteCustomer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        querySelect.setEditable(true);
        querySelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add Customer *", "Update Customer *", "Delete Customer *", "List of Customers *", "Assign Membership *", "Add Employee *", "Update Employee *", "Delete Employee *", "Get Employee *", "List of Employees *", "Add Membership *", "Update Membership *", "Delete Membership *", "List of Memberships *", "List of Roles *", "List of Rentals", "Movies In Stock", "Most Rented Movies", " " }));
        querySelect.setToolTipText("");
        querySelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                querySelectActionPerformed(evt);
            }
        });

        executeQuery.setText("Query");
        executeQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeQueryAction(evt);
            }
        });

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Database");
        title.setToolTipText("");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jScrollPane2.setViewportView(output);

        custFN.setText("First Name*");

        custLN.setText("Last Name*");

        custE.setText("Email*");

        custPN.setText("Phone Number*");

        jLabel1.setText("Add Customer");

        custM.setText("Membership");

        custD.setText("Date");

        addCustomerButton.setText("Add");
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });

        custID.setText("Customer ID");

        jLabel2.setText("Delete Customer");

        deleteCustomer.setText("Delete");
        deleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustomerAction(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(querySelect, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(title)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(custFN, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(custLN)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(executeQuery)
                                .addGap(378, 378, 378)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(custE)
                                    .addComponent(custPN, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(custD)
                                    .addComponent(custM)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addCustomerButton)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(deleteCustomer)))
                        .addGap(153, 153, 153))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(title)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(custFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(querySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(executeQuery)
                                .addGap(77, 77, 77)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(custE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addCustomerButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(deleteCustomer)))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void querySelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_querySelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_querySelectActionPerformed

    private void executeQueryAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeQueryAction
                                         
        
        output.setText(""); //reset textpanel to empty when making a new query
        
        StyledDocument doc = output.getStyledDocument();        
        Style bold = doc.addStyle("bold", null);       
        StyleConstants.setBold(bold, true);
        
        int size = 0;
        
        try{
            String selected = (String) querySelect.getSelectedItem();
            
            switch(selected){            
                case "List of Rentals":
                    
                    RentalDAO renDAO = new RentalDAO();
                    
                    List<Rental> rental = renDAO.getRentals();
                    size = rental.size();
                    String set = "";
                    for(int i = 0; i < size; i++){
                        Rental read = rental.get(i);
                        
                        doc.insertString(doc.getLength(), "Rental_Id: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getRentalID()), null);
                        doc.insertString(doc.getLength(), " Rental_Date: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getRentalDate()), null);
                        doc.insertString(doc.getLength(), " Customer_Id: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getCustomerID()), null);
                        doc.insertString(doc.getLength(), " Sold_By: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getSoldBy()), null);
                        doc.insertString(doc.getLength(), "\n", bold);

                    }
                    
                    break;           
                case "Movies In Stock":
                    
                    InventoryStockedDAO invDAO = new InventoryStockedDAO();
                    List<InventoryStocked> inventory = invDAO.getInventoryStocked();
                    size = inventory.size();
                    for(int i = 0; i < size; i++){
                        InventoryStocked read = inventory.get(i);
                    
                        doc.insertString(doc.getLength(), "Movie_Title: ", bold);
                        doc.insertString(doc.getLength(), read.getMovie_title(), null);
                        doc.insertString(doc.getLength(), " Inventory_Id: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getInventory_id()), null);
                        doc.insertString(doc.getLength(), " In_Stock: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getIn_stock()), null);
                        doc.insertString(doc.getLength(), "\n", bold);
                        
                    }

                    break;
                case "Most Rented Movies":
                    
                    MostRentedDAO mrDAO = new MostRentedDAO();                   
                    List<MostRented> mostRented = mrDAO.getMostRented();
                    size = mostRented.size();
                    for(int i = 0; i < size; i++){
                        MostRented read = mostRented.get(i);
                    
                        doc.insertString(doc.getLength(), "Movie_Title: ", bold);
                        doc.insertString(doc.getLength(), read.getMovie_title(), null);
                        doc.insertString(doc.getLength(), " Times Rented: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getTimes_rented()), null);
                        doc.insertString(doc.getLength(), "\n", bold);
                        
                    }
                    
                    break;
                case "Add Customer *":
                    
                    output.setText("Enter First Name:");
                    customerAddState = "FN";
                    
            }
        }
        catch(SQLException sql){
            System.out.println("SQL Swing");
        }
        catch(BadLocationException ble){
            System.out.println("Bad Location");
        }
              
    }//GEN-LAST:event_executeQueryAction

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
        
        output.setText("");
        
        try{
            Customer toAdd = new Customer(custFN.getText(), custLN.getText(), custE.getText(), custPN.getText(), Integer.parseInt(custM.getText()), LocalDate.parse(custD.getText()));
        
            CustomerDao add = new CustomerDao();
        
            add.addCustomer(toAdd);
        }
        catch(Exception e){
            output.setText("Invalid Input. Please check all fields");
        }
        
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    private void deleteCustomerAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomerAction
        
        try{
            int toDelete = Integer.parseInt(custID.getText());
            CustomerDao delete = new CustomerDao();
            delete.deleteCustomer(toDelete);
        }
        catch(NumberFormatException e){
            output.setText("Invalid Customer ID");
        }
        
        
    }//GEN-LAST:event_deleteCustomerAction

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JTextField custD;
    private javax.swing.JTextField custE;
    private javax.swing.JTextField custFN;
    private javax.swing.JTextField custID;
    private javax.swing.JTextField custLN;
    private javax.swing.JTextField custM;
    private javax.swing.JTextField custPN;
    private javax.swing.JButton deleteCustomer;
    private javax.swing.JButton executeQuery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane output;
    private javax.swing.JComboBox<String> querySelect;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
