package movieproject;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author awday
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        querySelect = new javax.swing.JComboBox<>();
        executeQuery = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        querySelect.setEditable(true);
        querySelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rentals", "Movies In Stock", "Most Rented Movies" }));
        querySelect.setToolTipText("");
        querySelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                querySelectActionPerformed(evt);
            }
        });

        executeQuery.setText("Query");
        executeQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeQueryAction(evt);
            }
        });

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Database");
        title.setToolTipText("");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jScrollPane2.setViewportView(output);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(querySelect, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(executeQuery))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(title)))
                .addGap(255, 255, 255))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(title)
                .addGap(24, 24, 24)
                .addComponent(querySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(executeQuery)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void querySelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_querySelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_querySelectActionPerformed

    private void executeQueryAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeQueryAction
                                         
        
        output.setText(""); //reset textpanel to empty when making a new query
        
        StyledDocument doc = output.getStyledDocument();        
        Style bold = doc.addStyle("bold", null);       
        StyleConstants.setBold(bold, true);
        
        int size = 0;
        
        try{
            String selected = (String) querySelect.getSelectedItem();
            
            switch(selected){            
                case "Rentals":
                    
                    RentalDAO renDAO = new RentalDAO();
                    
                    List<Rental> rental = renDAO.getRentals();
                    size = rental.size();
                    String set = "";
                    for(int i = 0; i < size; i++){
                        Rental read = rental.get(i);
                        
                        doc.insertString(doc.getLength(), "Rental_Id: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getRentalID()), null);
                        doc.insertString(doc.getLength(), " Rental_Date: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getRentalDate()), null);
                        doc.insertString(doc.getLength(), " Customer_Id: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getCustomerID()), null);
                        doc.insertString(doc.getLength(), " Sold_By: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getSoldBy()), null);
                        doc.insertString(doc.getLength(), "\n", bold);

                    }
                    
                    break;           
                case "Movies In Stock":
                    
                    InventoryStockedDAO invDAO = new InventoryStockedDAO();
                    List<InventoryStocked> inventory = invDAO.getInventoryStocked();
                    size = inventory.size();
                    for(int i = 0; i < size; i++){
                        InventoryStocked read = inventory.get(i);
                    
                        doc.insertString(doc.getLength(), "Movie_Title: ", bold);
                        doc.insertString(doc.getLength(), read.getMovie_title(), null);
                        doc.insertString(doc.getLength(), " Inventory_Id: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getInventory_id()), null);
                        doc.insertString(doc.getLength(), " In_Stock: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getIn_stock()), null);
                        doc.insertString(doc.getLength(), "\n", bold);
                        
                }

                    break;
                case "Most Rented Movies":
                    
                    MostRentedDAO mrDAO = new MostRentedDAO();                   
                    List<MostRented> mostRented = mrDAO.getMostRented();
                    size = mostRented.size();
                    for(int i = 0; i < size; i++){
                        MostRented read = mostRented.get(i);
                    
                        doc.insertString(doc.getLength(), "Movie_Title: ", bold);
                        doc.insertString(doc.getLength(), read.getMovie_title(), null);
                        doc.insertString(doc.getLength(), " Times Rented: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getTimes_rented()), null);
                        doc.insertString(doc.getLength(), "\n", bold);
                        
                }

            }
        }
        catch(SQLException sql){
            System.out.println("SQL Swing");
        }
        catch(BadLocationException ble){
            System.out.println("Bad Location");
        }
              
    }//GEN-LAST:event_executeQueryAction

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton executeQuery;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane output;
    private javax.swing.JComboBox<String> querySelect;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
