

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import java.time.LocalDate;
import java.math.BigDecimal;

/**
 *
 * @author awday
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    
    private String customerAddState = "";
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        querySelect = new javax.swing.JComboBox<>();
        executeQuery = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextPane();
        custFN = new javax.swing.JTextField();
        custLN = new javax.swing.JTextField();
        custE = new javax.swing.JTextField();
        custPN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        custM = new javax.swing.JTextField();
        custD = new javax.swing.JTextField();
        addCustomerButton = new javax.swing.JButton();
        custID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        deleteCustomer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        uCustFN = new javax.swing.JTextField();
        uCustIDMem = new javax.swing.JTextField();
        uCustLN = new javax.swing.JTextField();
        uCustE = new javax.swing.JTextField();
        uCustMID = new javax.swing.JTextField();
        uCustPN = new javax.swing.JTextField();
        updateCustomerButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        empFN = new javax.swing.JTextField();
        empLN = new javax.swing.JTextField();
        empPN = new javax.swing.JTextField();
        empR = new javax.swing.JTextField();
        addEmployeeButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        empID = new javax.swing.JTextField();
        deleteEmployeeButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        uEmpR = new javax.swing.JTextField();
        uEmpID = new javax.swing.JTextField();
        updateEmployeeButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        movieP = new javax.swing.JTextField();
        movieT = new javax.swing.JTextField();
        addMovieButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        movieID = new javax.swing.JTextField();
        deleteMovieButton = new javax.swing.JButton();
        lRoleID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        listEmployeeButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        uCustID = new javax.swing.JTextField();
        uCustM = new javax.swing.JTextField();
        updateCustomerMembershipButton = new javax.swing.JButton();
        updateMovieButton = new javax.swing.JButton();
        uMovieID = new javax.swing.JTextField();
        uMovieT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        uMovieP = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        invMovieID = new javax.swing.JTextField();
        addMovieToInventory = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        invID = new javax.swing.JTextField();
        deleteMovieFromInventory = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        querySelect.setEditable(true);
        querySelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "List of Customers", "List of Employees", "List of Memberships", "List of Roles", "List of Rentals", "List of Movies", "Movies In Stock", "Most Rented Movies" }));
        querySelect.setToolTipText("");
        getContentPane().add(querySelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 630, 234, -1));

        executeQuery.setText("Query");
        executeQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeQueryAction(evt);
            }
        });
        getContentPane().add(executeQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 670, -1, -1));

        title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("General Queries");
        title.setToolTipText("");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 580, -1, -1));

        jScrollPane2.setViewportView(output);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 1070, 251));

        custFN.setText("First Name");
        getContentPane().add(custFN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 111, -1));

        custLN.setText("Last Name");
        getContentPane().add(custLN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 111, -1));

        custE.setText("Email");
        getContentPane().add(custE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 111, -1));

        custPN.setText("Phone Number");
        getContentPane().add(custPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 111, -1));

        jLabel1.setText("Add Customer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        custM.setText("Membership ID");
        getContentPane().add(custM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 111, -1));

        custD.setText("Date");
        getContentPane().add(custD, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 111, -1));

        addCustomerButton.setText("Add");
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addCustomerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        custID.setText("Customer ID");
        getContentPane().add(custID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 110, -1));

        jLabel2.setText("Delete Customer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        deleteCustomer.setText("Delete");
        deleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustomerAction(evt);
            }
        });
        getContentPane().add(deleteCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        jLabel3.setText("Update Customer");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        uCustFN.setText("First Name");
        getContentPane().add(uCustFN, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 115, -1));

        uCustIDMem.setText("Customer ID");
        getContentPane().add(uCustIDMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 115, -1));

        uCustLN.setText("Last Name");
        getContentPane().add(uCustLN, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 115, -1));

        uCustE.setText("Email");
        getContentPane().add(uCustE, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 115, -1));

        uCustMID.setText("Membership ID");
        getContentPane().add(uCustMID, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 115, -1));

        uCustPN.setText("Phone Number");
        getContentPane().add(uCustPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 115, -1));

        updateCustomerButton.setText("Update");
        updateCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerAction(evt);
            }
        });
        getContentPane().add(updateCustomerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, -1, -1));

        jLabel4.setText("Add Employee");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, -1, -1));

        empFN.setText("First Name");
        getContentPane().add(empFN, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 110, -1));

        empLN.setText("Last Name");
        getContentPane().add(empLN, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 110, -1));

        empPN.setText("Phone Number");
        getContentPane().add(empPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 110, -1));

        empR.setText("Role ID");
        getContentPane().add(empR, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 110, -1));

        addEmployeeButton.setText("Add");
        addEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeAction(evt);
            }
        });
        getContentPane().add(addEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, -1, -1));

        jLabel5.setText("Delete Employee");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, -1, -1));

        empID.setText("Employee ID");
        getContentPane().add(empID, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 110, -1));

        deleteEmployeeButton.setText("Delete");
        deleteEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmployeeAction(evt);
            }
        });
        getContentPane().add(deleteEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, -1, -1));

        jLabel6.setText("Update Employee Role");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, 150, -1));

        uEmpR.setText("Role ID");
        getContentPane().add(uEmpR, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 390, 112, -1));

        uEmpID.setText("Employee ID");
        getContentPane().add(uEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 360, 112, -1));

        updateEmployeeButton.setText("Update");
        updateEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeAction(evt);
            }
        });
        getContentPane().add(updateEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, -1, -1));

        jLabel7.setText("Add Movie");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, -1, -1));

        movieP.setText("Movie Price");
        getContentPane().add(movieP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, 112, -1));

        movieT.setText("Movie Title");
        getContentPane().add(movieT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 112, -1));

        addMovieButton.setText("Add");
        addMovieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMovieAction(evt);
            }
        });
        getContentPane().add(addMovieButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 700, -1, -1));

        jLabel8.setText("Delete Movie");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, -1, -1));

        movieID.setText("Movie ID");
        getContentPane().add(movieID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, 112, -1));

        deleteMovieButton.setText("Delete");
        deleteMovieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMovieAction(evt);
            }
        });
        getContentPane().add(deleteMovieButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 670, -1, -1));

        lRoleID.setText("Role ID");
        getContentPane().add(lRoleID, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 360, 100, -1));

        jLabel9.setText("List Employees By Role");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 340, 130, -1));

        listEmployeeButton.setText("List");
        listEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listEmployeeByRoleAction(evt);
            }
        });
        getContentPane().add(listEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 390, -1, -1));

        jLabel10.setText("Update Customer Membership");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        uCustID.setText("Customer ID");
        getContentPane().add(uCustID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 115, -1));

        uCustM.setText("Membership ID");
        getContentPane().add(uCustM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 115, -1));

        updateCustomerMembershipButton.setText("Update");
        updateCustomerMembershipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerMembershipAction(evt);
            }
        });
        getContentPane().add(updateCustomerMembershipButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, -1, -1));

        updateMovieButton.setText("Update");
        updateMovieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMovieAction(evt);
            }
        });
        getContentPane().add(updateMovieButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 730, -1, -1));

        uMovieID.setText("Movie ID");
        getContentPane().add(uMovieID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, 120, -1));

        uMovieT.setText("Movie Title");
        getContentPane().add(uMovieT, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 670, 120, -1));

        jLabel11.setText("Update Movie");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 620, 80, -1));

        uMovieP.setText("Movie Price");
        getContentPane().add(uMovieP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 700, 120, -1));

        jLabel12.setText("Add Movie to Inventory");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, -1, -1));

        invMovieID.setText("Movie ID");
        getContentPane().add(invMovieID, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 640, 110, -1));

        addMovieToInventory.setText("Add");
        addMovieToInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMovieToInventoryAction(evt);
            }
        });
        getContentPane().add(addMovieToInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 670, -1, -1));

        jLabel13.setText("Delete Movie From Inventory");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, -1, -1));

        invID.setText("Inventory ID");
        getContentPane().add(invID, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 640, 110, -1));

        deleteMovieFromInventory.setText("Delete");
        deleteMovieFromInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMovieFromInventoryAction(evt);
            }
        });
        getContentPane().add(deleteMovieFromInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 670, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("Employee");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 110, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("Movie Inventory");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 580, 180, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setText("Customer");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 110, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setText("Movie");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executeQueryAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeQueryAction
                                         
        
        output.setText(""); //reset textpanel to empty when making a new query
        
        StyledDocument doc = output.getStyledDocument();        
        Style bold = doc.addStyle("bold", null);       
        StyleConstants.setBold(bold, true);
        
        int size = 0;
        
        try{
            String selected = (String) querySelect.getSelectedItem();
            
            switch(selected){            
                case "List of Rentals":
                    
                    RentalDAO renDAO = new RentalDAO();
                    
                    List<Rental> rental = renDAO.getRentals();
                    size = rental.size();
                    String set = "";
                    for(int i = 0; i < size; i++){
                        Rental read = rental.get(i);
                        
                        doc.insertString(doc.getLength(), "Rental_Id: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getRentalID()), null);
                        doc.insertString(doc.getLength(), " Rental_Date: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getRentalDate()), null);
                        doc.insertString(doc.getLength(), " Customer_Id: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getCustomerID()), null);
                        doc.insertString(doc.getLength(), " Customer First Name: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getCustFirstName()), null);
                        doc.insertString(doc.getLength(), " Customer Last Name: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getCustLastName()), null);
                        doc.insertString(doc.getLength(), " Sold_By: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getSoldBy()), null);
                        doc.insertString(doc.getLength(), " Employee First Name: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getEmpFirstName()), null);
                        doc.insertString(doc.getLength(), " Total Price: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getTotalPrice()), null);
                        doc.insertString(doc.getLength(), "\n", bold);

                    }
                    
                    break;           
                case "Movies In Stock":
                    
                    InventoryStockedDAO invDAO = new InventoryStockedDAO();
                    List<InventoryStocked> inventory = invDAO.getInventoryStocked();
                    size = inventory.size();
                    for(int i = 0; i < size; i++){
                        InventoryStocked read = inventory.get(i);
                    
                        doc.insertString(doc.getLength(), "Movie_Title: ", bold);
                        doc.insertString(doc.getLength(), read.getMovie_title(), null);
                        doc.insertString(doc.getLength(), " Inventory_Id: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getInventory_id()), null);
                        doc.insertString(doc.getLength(), " In_Stock: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getIn_stock()), null);
                        doc.insertString(doc.getLength(), "\n", bold);
                        
                    }

                    break;
                case "Most Rented Movies":
                    
                    MostRentedDAO mrDAO = new MostRentedDAO();                   
                    List<MostRented> mostRented = mrDAO.getMostRented();
                    size = mostRented.size();
                    for(int i = 0; i < size; i++){
                        MostRented read = mostRented.get(i);
                    
                        doc.insertString(doc.getLength(), "Movie_Title: ", bold);
                        doc.insertString(doc.getLength(), read.getMovie_title(), null);
                        doc.insertString(doc.getLength(), " Times Rented: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getTimes_rented()), null);
                        doc.insertString(doc.getLength(), "\n", bold);
                        
                    }
                    
                    break;
                case "List of Customers":
                       
                    CustomerDao custDAO = new CustomerDao();
                    List<CustomerMembershipView> custList = custDAO.getAllCustomers();
                    size = custList.size();
                    for(int i = 0; i < size; i++){
                        CustomerMembershipView read = custList.get(i);
                    
                        doc.insertString(doc.getLength(), "Customer ID: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getCustomerId()), null);
                        doc.insertString(doc.getLength(), " First Name: ", bold);
                        doc.insertString(doc.getLength(), read.getFirstName(), null);
                        doc.insertString(doc.getLength(), " Last Name: ", bold);
                        doc.insertString(doc.getLength(), read.getLastName(), null);
                        doc.insertString(doc.getLength(), " Email: ", bold);
                        doc.insertString(doc.getLength(), read.getEmail(), null);
                        doc.insertString(doc.getLength(), " Phone: ", bold);
                        doc.insertString(doc.getLength(), read.getPhone(), null);
                        doc.insertString(doc.getLength(), " Membership: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getMembershipType()), null);
                        doc.insertString(doc.getLength(), " Discount: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getDiscountPercent()), null);
                        doc.insertString(doc.getLength(), " Date: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getCreatedDate()), null);
                        doc.insertString(doc.getLength(), "\n", bold);
                        
                    }
                    
                    
                    break;
                    
                case "List of Employees":
                    
                    EmployeeDao empDAO = new EmployeeDao();
                    List<EmployeeRoleView> empList = empDAO.getAllEmployees();
                    size = empList.size();
                    for(int i = 0; i < size; i++){
                        EmployeeRoleView read = empList.get(i);
                        
                        doc.insertString(doc.getLength(), "Employee ID: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getEmployeeId()), null);
                        doc.insertString(doc.getLength(), " First Name: ", bold);
                        doc.insertString(doc.getLength(), read.getFirstName(), null);
                        doc.insertString(doc.getLength(), " Last Name: ", bold);
                        doc.insertString(doc.getLength(), read.getLastName(), null);
                        doc.insertString(doc.getLength(), " Phone: ", bold);
                        doc.insertString(doc.getLength(), read.getPhone(), null);
                        doc.insertString(doc.getLength(), " Role Type: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getRoleType()), null);
                        doc.insertString(doc.getLength(), "\n", bold);
                        
                    }
                                       
                    break;
                    
                case "List of Roles":
                    
                    RoleDao roleDAO = new RoleDao();
                    List<Role> roleList = roleDAO.getAllRoles();
                    size = roleList.size();
                    for(int i = 0; i < size; i++){
                        Role read = roleList.get(i);
                        
                        doc.insertString(doc.getLength(), "Role ID: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getRoleId()), null);
                        doc.insertString(doc.getLength(), " Role Type: ", bold);
                        doc.insertString(doc.getLength(), read.getRoleType(), null);
                        doc.insertString(doc.getLength(), "\n", bold);

                        
                    }
                    break;
                    
                case "List of Memberships":
                    
                    MembershipDao memDAO = new MembershipDao();
                    List<Membership> memList = memDAO.getAllMemberships();
                    size = memList.size();
                    for(int i = 0; i < size; i++){
                        Membership read = memList.get(i);
                        
                        doc.insertString(doc.getLength(), "Membership ID: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getMembershipId()), null);
                        doc.insertString(doc.getLength(), " Membership Type: ", bold);
                        doc.insertString(doc.getLength(), read.getMembershipType(), null);
                        doc.insertString(doc.getLength(), " Discount: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getDiscountPercent()), null);
                        doc.insertString(doc.getLength(), "\n", bold);

                        
                    }
                    break;
                    
                case "List of Movies":
                    
                    MovieDao movieDAO = new MovieDao();
                    List<Movie> movieList = movieDAO.getAllMovies();
                    size = movieList.size();
                    for(int i = 0; i < size; i++){
                        Movie read = movieList.get(i);
                        
                        doc.insertString(doc.getLength(), "Movie ID: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getMovieId()), null);
                        doc.insertString(doc.getLength(), " Movie Title: ", bold);
                        doc.insertString(doc.getLength(), read.getTitle(), null);
                        doc.insertString(doc.getLength(), " Price: ", bold);
                        doc.insertString(doc.getLength(), String.valueOf(read.getMoviePrice()), null);
                        doc.insertString(doc.getLength(), "\n", bold);

                        
                    }
                    break;
            }
        }
        catch(SQLException sql){
            System.out.println("SQL Swing");
        }
        catch(BadLocationException ble){
            System.out.println("Bad Location");
        }
              
    }//GEN-LAST:event_executeQueryAction

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
        
        output.setText("");
        
        try{
            Customer toAdd = new Customer(custFN.getText(), custLN.getText(), custE.getText(), custPN.getText(), Integer.parseInt(custM.getText()), LocalDate.parse(custD.getText()));
        
            CustomerDao add = new CustomerDao();
        
            add.addCustomer(toAdd);
            
            output.setText("Successful Query");
        }
        catch(Exception e){
            output.setText("Invalid Input. Please check all fields");
        }
        
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    private void deleteCustomerAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomerAction
        
        try{
            int toDelete = Integer.parseInt(custID.getText());
            CustomerDao delete = new CustomerDao();
            delete.deleteCustomer(toDelete);
            
            output.setText("Successful Query");
        }
        catch(NumberFormatException e){
            output.setText("Invalid Customer ID");
        }
        
        
    }//GEN-LAST:event_deleteCustomerAction

    private void updateCustomerAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerAction
        
        output.setText("");
        
        try{

            Customer toUpdate = new Customer(Integer.parseInt(uCustID.getText()), uCustFN.getText(), uCustLN.getText(), uCustE.getText(), uCustPN.getText(), Integer.parseInt(uCustM.getText()), null);
        
            CustomerDao update = new CustomerDao();
        
            update.updateCustomer(toUpdate);
            
            output.setText("Successful Query");
        }
        catch(Exception e){
            output.setText("Invalid Input. Please check all fields");
        }
        
    }//GEN-LAST:event_updateCustomerAction

    private void addEmployeeAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeAction
        
        output.setText("");
        
        try{
            Employee toAdd = new Employee(empFN.getText(), empLN.getText(), empPN.getText(), Integer.parseInt(empR.getText()));
        
            EmployeeDao add = new EmployeeDao();
        
            add.addEmployee(toAdd);
            
            output.setText("Successful Query");
        }
        catch(Exception e){
            output.setText("Invalid Input. Please check all fields");
        }
        

    }//GEN-LAST:event_addEmployeeAction

    private void deleteEmployeeAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmployeeAction

        try{
            int toDelete = Integer.parseInt(empID.getText());
            EmployeeDao delete = new EmployeeDao();
            delete.deleteEmployee(toDelete);
            
            output.setText("Successful Query");
        }
        catch(NumberFormatException e){
            output.setText("Invalid Customer ID");
        }
        
    }//GEN-LAST:event_deleteEmployeeAction

    private void updateEmployeeAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeAction
        
        output.setText("");
        
        try{
            
            EmployeeDao update = new EmployeeDao();
        
            update.updateEmployeeRole(Integer.parseInt(uEmpID.getText()), Integer.parseInt(uEmpR.getText()));
            
            output.setText("Successful Query");
        }
        catch(Exception e){
            output.setText("Invalid Input. Please check all fields");
        }

    }//GEN-LAST:event_updateEmployeeAction

    private void addMovieAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMovieAction
        
        output.setText("");
        
        try{
        
            MovieDao add = new MovieDao();
        
            add.addMovie(movieT.getText(), BigDecimal.valueOf(Double.parseDouble(movieP.getText())));
            
            output.setText("Successful Query");
        }
        catch(Exception e){
            output.setText("Invalid Input. Please check all fields");
        }
        
        
    }//GEN-LAST:event_addMovieAction

    private void deleteMovieAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMovieAction
        
        
        try{
            int toDelete = Integer.parseInt(movieID.getText());
            MovieDao delete = new MovieDao();
            delete.deleteMovie(toDelete);
            
            output.setText("Successful Query");
        }
        catch(NumberFormatException e){
            output.setText("Invalid Movie ID");
        }
        
        
    }//GEN-LAST:event_deleteMovieAction

    private void listEmployeeByRoleAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listEmployeeByRoleAction
        
        output.setText("");
        
         try{
            StyledDocument doc = output.getStyledDocument();        
            Style bold = doc.addStyle("bold", null);       
            StyleConstants.setBold(bold, true);

            EmployeeDao empDAO = new EmployeeDao();
            RoleDao roleDAO = new RoleDao();
            List<EmployeeRoleView> empList = empDAO.getEmployeesByRole(Integer.parseInt(lRoleID.getText()));
            int size = empList.size();
            
            if(!roleDAO.roleExists(Integer.parseInt(lRoleID.getText()))) {
                output.setText("Role ID does not exist");
                return;
            }
            if(empList.isEmpty()){
                output.setText("No Employees found for that role ID.");
                return;
            } else {
            for(int i = 0; i < size; i++){
                EmployeeRoleView read = empList.get(i);

                doc.insertString(doc.getLength(), "Employee ID: ", bold);
                doc.insertString(doc.getLength(), String.valueOf(read.getEmployeeId()), null);
                doc.insertString(doc.getLength(), " First Name: ", bold);
                doc.insertString(doc.getLength(), read.getFirstName(), null);
                doc.insertString(doc.getLength(), " Last Name: ", bold);
                doc.insertString(doc.getLength(), read.getLastName(), null);
                doc.insertString(doc.getLength(), " Phone: ", bold);
                doc.insertString(doc.getLength(), read.getPhone(), null);
                doc.insertString(doc.getLength(), " Role Type: ", bold);
                doc.insertString(doc.getLength(), String.valueOf(read.getRoleType()), null);
                doc.insertString(doc.getLength(), "\n", bold);
            }
            }
        }
        catch(BadLocationException ble){
            output.setText("Invalid Input");
        }
        
        
    }//GEN-LAST:event_listEmployeeByRoleAction

    private void updateCustomerMembershipAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerMembershipAction
        
        output.setText("");
        
       try{
        
            Customer toUpdate = new Customer(Integer.parseInt(uCustID.getText()), uCustFN.getText(), uCustLN.getText(), uCustE.getText(), uCustPN.getText(), Integer.parseInt(uCustMID.getText()), null);
        
            CustomerDao update = new CustomerDao();
            MembershipDao membership = new MembershipDao();
        
            if(!update.customerExists(Integer.parseInt(uCustID.getText()))){
                output.setText("Customer ID does not exist.");
                return;
            }
            if(!membership.membershipExists(Integer.parseInt(uCustMID.getText()))){
                output.setText("Membership ID does not exist.");
                return;
            }
            if(update.updateCustomer(toUpdate)){
            output.setText("Customer updated successfully");
            } else {
                output.setText("Customer was not updated");
            }
            
        }
        catch(Exception e){
            output.setText("Invalid Input. Please check all fields");
        }
        
        
        
    }//GEN-LAST:event_updateCustomerMembershipAction

    private void updateMovieAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMovieAction
        
        output.setText("");
        
        try{
            
            MovieDao update = new MovieDao();
        
            update.editMovie(Integer.parseInt(uMovieID.getText()), uMovieT.getText(), BigDecimal.valueOf(Double.parseDouble(uMovieP.getText())));
            
            output.setText("Successful Query");
            
        }
        catch(Exception e){
            output.setText("Invalid Input. Please check all fields");
        }
        
        
        
    }//GEN-LAST:event_updateMovieAction

    private void addMovieToInventoryAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMovieToInventoryAction
        
        output.setText("");
        
        try{
        
            MovieInventoryDAO add = new MovieInventoryDAO();
        
            add.addMovieToInventory(Integer.parseInt(invMovieID.getText()));
            
            output.setText("Successful Query");
        }
        catch(Exception e){
            output.setText("Invalid Input. Please check all fields");
        }
        
    }//GEN-LAST:event_addMovieToInventoryAction

    private void deleteMovieFromInventoryAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMovieFromInventoryAction
        
        try{
            int toDelete = Integer.parseInt(invID.getText());
            MovieInventoryDAO delete = new MovieInventoryDAO();
            delete.deleteMovieFromInventory(toDelete);
            
            output.setText("Successful Query");
        }
        catch(NumberFormatException e){
            output.setText("Invalid Movie ID");
        }

    }//GEN-LAST:event_deleteMovieFromInventoryAction

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JButton addEmployeeButton;
    private javax.swing.JButton addMovieButton;
    private javax.swing.JButton addMovieToInventory;
    private javax.swing.JTextField custD;
    private javax.swing.JTextField custE;
    private javax.swing.JTextField custFN;
    private javax.swing.JTextField custID;
    private javax.swing.JTextField custLN;
    private javax.swing.JTextField custM;
    private javax.swing.JTextField custPN;
    private javax.swing.JButton deleteCustomer;
    private javax.swing.JButton deleteEmployeeButton;
    private javax.swing.JButton deleteMovieButton;
    private javax.swing.JButton deleteMovieFromInventory;
    private javax.swing.JTextField empFN;
    private javax.swing.JTextField empID;
    private javax.swing.JTextField empLN;
    private javax.swing.JTextField empPN;
    private javax.swing.JTextField empR;
    private javax.swing.JButton executeQuery;
    private javax.swing.JTextField invID;
    private javax.swing.JTextField invMovieID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lRoleID;
    private javax.swing.JButton listEmployeeButton;
    private javax.swing.JTextField movieID;
    private javax.swing.JTextField movieP;
    private javax.swing.JTextField movieT;
    private javax.swing.JTextPane output;
    private javax.swing.JComboBox<String> querySelect;
    private javax.swing.JLabel title;
    private javax.swing.JTextField uCustE;
    private javax.swing.JTextField uCustFN;
    private javax.swing.JTextField uCustID;
    private javax.swing.JTextField uCustIDMem;
    private javax.swing.JTextField uCustLN;
    private javax.swing.JTextField uCustM;
    private javax.swing.JTextField uCustMID;
    private javax.swing.JTextField uCustPN;
    private javax.swing.JTextField uEmpID;
    private javax.swing.JTextField uEmpR;
    private javax.swing.JTextField uMovieID;
    private javax.swing.JTextField uMovieP;
    private javax.swing.JTextField uMovieT;
    private javax.swing.JButton updateCustomerButton;
    private javax.swing.JButton updateCustomerMembershipButton;
    private javax.swing.JButton updateEmployeeButton;
    private javax.swing.JButton updateMovieButton;
    // End of variables declaration//GEN-END:variables
}
