import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Dylan Rattai
 * Data Access Object for Movie. Handles all CRUD operations for the movie table.
 * Delegates inventory management to MovieInventoryDAO.
 * Relationship: One Movie -> Many MovieInventory records.
 */
public class MovieDao {

    // Delegate inventory operations to MovieInventoryDAO
    private MovieInventoryDAO movieInventoryDAO = new MovieInventoryDAO();

    /**
     * Adds a new movie record to the database.
     * movie_id is auto-generated by the database (SERIAL).
     * Note: Inventory copies are managed separately via MovieInventoryDAO.addMovieToInventory().
     * Call this method first, then add inventory copies as needed.
     *
     * @param movieTitle The title of the movie.
     * @param moviePrice The price of the movie.
     * @return true if the movie was added successfully, false otherwise.
     */
    public boolean addMovie(String movieTitle, BigDecimal moviePrice) {
        String sqlStatement = "INSERT INTO movie (movie_title, rent_price) VALUES (?, ?)";

        try (Connection conn = DBManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sqlStatement)) {

            stmt.setString(1, movieTitle);
            stmt.setBigDecimal(2, moviePrice);

            int rowsInserted = stmt.executeUpdate();
            if (rowsInserted > 0) {
                System.out.println("Movie added successfully.");
            } else {
                throw new SQLException("Failed to add movie.");
            }

        } catch (SQLException e) {
            System.out.println("Error adding movie: " + e.getMessage());
            return false;
        }

        return true;
    }

    /**
     * Edits an existing movie's title and price in the database.
     *
     * @param movieId    The unique identifier for the movie to update.
     * @param movieTitle The new title of the movie.
     * @param moviePrice The new price of the movie.
     * @return true if the movie was updated successfully, false otherwise.
     */
    public boolean editMovie(int movieId, String movieTitle, BigDecimal moviePrice) {
        String sqlStatement = "UPDATE movie SET movie_title = ?, rent_price = ? WHERE movie_id = ?";

        try (Connection conn = DBManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sqlStatement)) {

            stmt.setString(1, movieTitle);
            stmt.setBigDecimal(2, moviePrice);
            stmt.setInt(3, movieId);

            int rowsUpdated = stmt.executeUpdate();
            if (rowsUpdated > 0) {
                System.out.println("Movie updated successfully.");
            } else {
                throw new SQLException("No movie found with the given ID.");
            }

        } catch (SQLException e) {
            System.out.println("Error updating movie: " + e.getMessage());
            return false;
        }

        return true;
    }

    /**
     * Deletes a movie from the database based on the provided movie ID.
     * All associated inventory records are removed first via MovieInventoryDAO
     * to avoid foreign key constraint violations (one movie -> many inventory rows).
     *
     * @param movieId The unique identifier for the movie to be deleted.
     * @return true if the movie and its inventory were deleted successfully, false otherwise.
     */
    public boolean deleteMovie(int movieId) {
        // Remove all linked inventory rows first before deleting the movie
        // This prevents FK constraint violations since inventory references movie_id
        if (!movieInventoryDAO.deleteAllForMovie(movieId)) {
            System.out.println("Failed to remove inventory records. Movie deletion aborted.");
            return false;
        }

        String sqlStatement = "DELETE FROM movie WHERE movie_id = ?";

        try (Connection conn = DBManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sqlStatement)) {

            stmt.setInt(1, movieId);

            int rowsDeleted = stmt.executeUpdate();
            if (rowsDeleted > 0) {
                System.out.println("Movie deleted successfully.");
            } else {
                throw new SQLException("No movie found with the given ID.");
            }

        } catch (SQLException e) {
            System.out.println("Error deleting movie: " + e.getMessage());
            return false;
        }

        return true;
    }
    
    
    public List<Movie> getAllMovies() {
        List<Movie> rows = new ArrayList<>();

        String sql = """
            SELECT movie_id, movie_title, rent_price
            FROM movie
            ORDER BY movie_title desc
        """;

        try (Connection conn = DBManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                Movie movie = new Movie(
                    rs.getInt("movie_id"),
                    rs.getString("movie_title"),
                    BigDecimal.valueOf(rs.getDouble("rent_price"))
                );

                rows.add(movie);
            }

        } catch (SQLException e) {
            System.out.println("Error getting movies: " + e.getMessage());
        }

        return rows;
    }
    
    
}